name: trello_dart
version: 0.0.1
description: A Trello API Client for Dart.
author: joe_re<joe.tialtngo@gmail.com>
homepage: https://github.com/joe-re/trello-dart
#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'
